export const notices = [
    "Providing Central Sponsorship branding service to KMF Nandini brand for Pro Kabbaddi League",
    "Providing Secure QR codes for Nandini Ghee Sachets for a period of two years.",
    "SHORT TERM TENDER NOTIFICATION",
    "Supply of Cow Rubber Mat",
    "Supply of Laminated Film for packing 1kg Chelated Mineral Mixture to KMF Cattle Feed Plants",
    "Supply and installation of Disc Mower to Nandini Sperm Station, Hesaraghatta, Bengaluru",
    "Supply of E-Rikshaw to Karnataka Milk Federation",
    "TENDER NOTIFICATION – 2nd CAL",
    "SHORT TERM TENDER NOTIFICATION",
    "Raw Materials TENDER NOTIFICATION",
    "Raw Materials SHORT TERM TENDER NOTIFICATION",
    "ತಾಂತ್ರಿಕ ಹಾಗು ವಾಣಿಜ್ಯ ಟೆಂಡರ್",
    "Supply and Installation of Computers to KMF Units",
    "Providing promotion & branding service to KMF Nandini brand for Football Indian super League, 2024",
    "SHORT TERM TENDER NOTIFICATION in Mandya Milk Union Ltd",
    "FLECI PACK ARTWORK TENDER NOTIFICATION",
    "The Karnataka Milk Federation, invites Tenders from eligible Tenderers for supply of Raw Materials",
    "Insurance Tender Notification",
    "Supply Of Fire Wood(Dry) (Recall) Tender Notification",
    "Tender Notification Supply of Fuel Briquettes",
    "The Karnataka Milk Federation Ltd., invites tenders for supply of Belt Conveyor to gubbi cattle feed plant.",
    "Tender Notification",
    "Supply, Erection, Testing & Commissioning of 125 KVA Capacity BioGas Engine",
    "SHORT TERM TENDER NOTIFICATION",
    "SHORT TERM TENDER NOTIFICATION Raw material Molasses (Grade -A)",
    "Biannual Rate Contract For Providing Manpower For Operation And Maintenance",
    "SHORT TERM TENDER NOTIFICATION (Raw Materials)",
    "SHORT TERM E TENDER(Supply of Cow Rubber Mat)",
    "TECHNICAL CUM COMMERCIAL TENDER (Supply of Tarpaulin Bags and Jerkins)",
    "INVITATION FOR SHORT TERM E TENDER(IFT) TECHNICAL CUM COMMERCIAL TENDER",
    "DHAMUL mediclaim Insurance Tender Notifiation",
    "SHORT TERM TENDER NOTIFICATION (Raw Materials)",
    "PUBLIC AUCTION NOTICE-RAJANAKUNTE,BENGALURU",
    "Vehicle Tender Notification",
    "FOR SHORT-TERM E TENDER",
    "Expression of Interest (EOI) Document",
    "Expression of Interest",
    "TENDER FOR SALE OF SKIMMED MILK POWDER",
    "Tender for Procurement of up to 1MW RTC Firm Power",
    "DHARWAD SHORT TERM TENDER NOTIFICATION",
    "Dharwad Short term Tender for Liaisoning & Transportation of Steam Coal",
    "SHORT TERM E-TENDER NOTIFICATION",
    "DHARWAD E-TENDER NOTIFICATION",
    "Cattle Feed Tender Notification",
    "NATIONAL COMPETITIVE BIDDING FOR THE SUPPLY OF AMCU",
    "SHORT TERM TENDER NOTIFICATION - KMF",
    "Short term Tender Notification Dhamul (P&I and MKTG)",
    "Tender Notification for providing pest control service",
    "EXPRESSION OF INTEREST",
    "Tender Notification for supply of Raw Materials",
    "Tender Notification for supply of the following Raw Materials",
    "Tumkur Co-operative Milk Producer Societies Union Ltd. invites tenders",
    "Tender Notification for supply of the following Goods at DHAMUL",
    "Tender Notification for supply of the Raw Material",
    "Karnataka Milk Federation invites eligible ETP Turnkey contractors",
    "Tender Notification for ETP Turnkey contractors",
    "Tender Notification for the supply of item(s)",
    "Tender Notification for the supply of the items",
    "Tender Notification for eligible ETP Turnkey contractors. TUMUL",
    "Expression of Interest at Munnekolalu film plant",
];